#!/bin/bash

# ==================================================================================
#
# Work of the U.S. Department of the Navy, Naval Information Warfare Center Pacific.
# Released as open source under the MIT License.  See LICENSE file.
#
# ==================================================================================

set -euo pipefail

function usage() {
  echo "Usage: ${0##*/} DATA_DIR PID_FILE LOG_FILE"
  exit 1
}

if [[ "$#" -ne 3 ]]; then
  usage
fi

data_dir=$1
pid_file=$2
log_file=$3

if [[ -f "${pid_file}" ]]; then
  echo "PID file ${pid_file} already exists."
  exit 1
fi

minio server "${data_dir}" >> "${log_file}" 2>&1 &
MINIO_PID=$!
echo $MINIO_PID > "${pid_file}"

echo "Runing minio process with PID ${MINIO_PID}" | tee -a "${log_file}"